# SentinelAI Risk Assessment Model
# Personalized risk profiling and allocation optimization
# Uses behavioral economics and portfolio theory

model:
  name: "SentinelAI Risk Assessor"
  version: "1.0.0"
  type: "risk_profiling"
  framework: "bayesian_network"

training:
  dataset: "user_risk_profiles_2023-2025"
  features:
    - quiz_responses
    - transaction_history
    - portfolio_performance
    - market_experience
    - behavioral_patterns
    - demographic_factors
  algorithm: "bayesian_risk_network"
  accuracy: 0.91
  consistency_score: 0.88

features:
  - personalized_profiling: true
  - dynamic_risk_adjustment: true
  - behavioral_insights: true
  - portfolio_optimization: true
  - suspicious_detection: true

endpoints:
  - assess_risk: "/api/ai/risk/assess"
  - optimize_portfolio: "/api/ai/risk/optimize"
  - detect_suspicious: "/api/ai/risk/detect"

integration:
  contract: "RiskProfiler"
  triggers:
    - quiz_completed
    - profile_updated
    - allocation_requested
    - suspicious_pattern

configuration:
  risk_levels: ["conservative", "balanced", "aggressive"]
  quiz_questions: 7
  suspicious_threshold: 40
  rebalance_frequency: "24h"

allocation_rules:
  conservative:
    stablecoins: [70, 100]
    majors: [0, 20]
    altcoins: [0, 10]
  balanced:
    stablecoins: [30, 70]
    majors: [20, 60]
    altcoins: [5, 20]
  aggressive:
    stablecoins: [0, 30]
    majors: [40, 80]
    altcoins: [15, 50]

validation:
  - minimum_quiz_completion: 100
  - maximum_profile_changes: 3
  - verification_required: true
